config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :entries do
    resources :reviews
  end
  root 'entries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :reviews

after_validation :reverse_geocode,
if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
reverse_geocoded_by :latitude, :longitude

  def full_address
		[country, city, street].compact.join(‘, ‘)
	end
end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :entry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :description, :lat, :long, :photo, :latitude, :longitude)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.entry_id = params[:entry_id]

    @entry = Entry.find(params[:entry_id])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @entry, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:score, :reviewtext, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :entry_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :entry_description %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :entry_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :entry_longitude %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :entry_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>
<section class="box">
<h2 class="section-title">Entries</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td class='table__entry-name'><%= link_to entry.name, entry %></td>
        <td class="table__description"><%= entry.description %></td>
        <td><%= entry.photo %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<% @entries.each do |entry| %>
  <%= link_to entry, class:"box box--narrow box--solid entry" do %>
      <img src="<%= entry.photo%>" alt="">
      <h3><%= entry.name %></h3>
      <hr>
      <p><%= entry.description %></p>
      <hr>
  <%end%>

  <div class="entry-controls">
  <%= link_to 'Edit', edit_entry_path(entry) %>
  <%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<%end%>

</section>
<div class="box box--narrow">
  <%= link_to 'New Entry', new_entry_path %>

</div>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>
    <h2>Location</h3>
<section class="box">
  <h1 class='page-title'>
    <%= @entry.name %> <div class='score score--big'>
      <%= @entry.reviews.average(:score) %></div>
  </h1>

  <hr>
  <p>
    <%= @entry.description %>
  </p>

  <h3>Photo</h3>
  <%= image_tag @entry.photo %>

  <% unless @entry.latitude.nil? %>
      <h2>Location</h2>
    <h3>
      <strong>Latitude:</strong>
      <%= @entry.latitude %>
    </h3>

    <h3>
      <strong>Longitude:</strong>
      <%= @entry.longitude %>
    </h3>

    <h3>Address</h3>
    <%= Geocoder.address([@entry.latitude,@entry.longitude]) %>
    <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@entry.latitude},#{@entry.longitude}&markers=#{@entry.latitude},#{@entry.longitude}&zoom=17&size=640x400&key=AIzaSyD4piB0aUPWUPPe4voL8X3V1zwBOkQcOfw", class:"img-fluid img-rounded", alt:"#{@entry.name} en el mapa" %>
  <% end %>
</section>
<section class='box'>
  <h2 class='section-title'>Reviews:</h2>
  <hr>
  <ul class='row'>

    <% @entry.reviews.each do |entry| %>
      <li class='box box--narrow box--solid row__box'>
        <div class='score'><%= entry.score %></div>
        <%= image_tag entry.photo %>
        <hr>
        <p class='review-list__item__review-text'><%= entry.reviewtext %></p>
      </li>
    <% end %>
  </ul>

</section>
<div class="box box--narrow">

<%= link_to 'Review', new_entry_review_path(@entry) %>
|
<%= link_to 'Edit', edit_entry_path(@entry) %>
|
<%= link_to 'Back', entries_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
  </head>

  <body>
    <nav class='box box--narrow navbar'>
      <%= link_to entries_path, class:"nav__home__link" do%>
        <div class="nav__home">
          <i class='material-icons'>&#xE88A;</i>
        </div>
      <% end %>

      <ul class='navbar__right'>
        <% if user_signed_in? %>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="nav__log-in"><%= link_to 'Log In', new_user_session_path %></li>
        <li class="nav__sign-up"><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
    <p class="alert"><%= alert %></p>



    <%= yield %>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, url: entry_reviews_path) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Your Score (out of 5)'%>
    <%= form.number_field :score, in: 1...6, id: :review_score %>
  </div>

  <div class="field">
    <%= form.label 'Review Text' %>
    <%= form.text_area :reviewtext, id: :review_reviewtext %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :review_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Reviewtext</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.score %></td>
        <td><%= review.reviewtext %></td>
        <td><%= review.photo %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="box">

<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', entries_path %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @review.score %>
</p>

<p>
  <strong>Reviewtext:</strong>
  <%= @review.reviewtext %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @review.photo %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>